### ISSUE TITLE
We need the base project

### ISSUE THREAD

**Issue by timlinux** [kartoza/all-hands-workshop#6]

**Comment by amyburness** [comment]
We need a base map for the application

**Comment by EliVolsch** [comment]
@Jeremy-Prior Please test this feature

**Comment by EliVolsch** [comment]
Dimas please review the code to determine the validity

**Comment by Jeremy-Prior** [comment]
Base project contains
- Rivers
- Roads
- Landuse

![image](https://github.com/kartoza/all-hands-workshop/assets/100694811/d7bed3d5-dff2-4792-b305-a6f33d59e436)
